// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trips.Entities.Pics;

namespace Trips.Migrations.Pics
{
    /* REMOVED.
     * Picture storage, for the first 2 months of the project when pictures were stored in DB.
     * Commented code left for history.
    [DbContext(typeof(PicsContext))]
    [Migration("20200418160210_PictureFormats")]
    partial class PictureFormats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Trips.Entities.Pics.PicData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PicData");
                });
#pragma warning restore 612, 618
        }
    }
    */
}
